# What is this file? Check it out at https://github.com/makii42/gottaw !
excludes:
- .git
- .hg
- .vscode
- .idea
- '*-go-tmp-umask'
- vendor*
- golcov*
- '*mocks.go'
- mocks/*
- mock_*/*
- .wercker
pipeline:
- dep ensure
- go generate $(go list ./...)
- go build -v .
- go test -cover -v  $(go list ./...)
